#!/usr/bin/env bash
set -euo pipefail

# build_app.sh — compile Macus and assemble a portable Macus.app bundle.
# No Xcode required: uses the Swift Package Manager toolchain from Command Line Tools.
#
#   Usage: scripts/build_app.sh [debug|release]
#
# Developed by Harith Dilshan / h4rithd.com — built with the help of Claude Code.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

CONFIG="${1:-release}"
APP_NAME="Macus"
PRODUCT_NAME="Macus"
BUNDLE_ID="com.abrichardson.macus"
VERSION="$(cat "$ROOT/VERSION" 2>/dev/null || echo 0.1.0)"
BUILD_NUM="$(date +%Y%m%d%H%M)"

DIST="$ROOT/dist"
APP="$DIST/$APP_NAME.app"
MACOS_DIR="$APP/Contents/MacOS"
RES_DIR="$APP/Contents/Resources"

# SwiftPM embeds its resource fallback path. Use a neutral temporary build location.
BUILD_DIR=$(mktemp -d /tmp/macus-release.XXXXXX)
trap 'rm -rf "$BUILD_DIR"' EXIT
echo "▶ Building Macus ($CONFIG)…"
swift build --scratch-path "$BUILD_DIR" -c "$CONFIG" -Xswiftc -debug-prefix-map -Xswiftc "$ROOT=/src/Macus" -Xswiftc -file-prefix-map -Xswiftc "$ROOT=/src/Macus" -Xcc "-ffile-prefix-map=$ROOT=/src/Macus"
BIN_DIR="$(swift build --scratch-path "$BUILD_DIR" -c "$CONFIG" --show-bin-path)"
BIN="$BIN_DIR/$PRODUCT_NAME"

echo "▶ Assembling $APP …"
rm -rf "$APP"
mkdir -p "$MACOS_DIR" "$RES_DIR"
cp "$BIN" "$MACOS_DIR/$APP_NAME"
# Distribution binaries must not expose local debug/build paths.
strip -S "$MACOS_DIR/$APP_NAME"
if /usr/bin/strings "$MACOS_DIR/$APP_NAME" | /usr/bin/grep -E '/Users/[^/]+/' >/dev/null; then
  echo 'Refusing to package a binary containing a personal build path.' >&2
  exit 1
fi

# Copy any SPM resource bundles next to the executable.
shopt -s nullglob
# Copy only current declared resources; incremental SPM bundles can retain deleted files.
for b in "$BIN_DIR"/Macus_MacusKit.bundle; do
  target="$RES_DIR/$(basename "$b")"
  mkdir -p "$target"
  for item in distros.json windows-write.sh InventoryToolkit; do cp -R "$b/$item" "$target/"; done
  find "$target" -type d -name __pycache__ -exec rm -rf {} +
done
shopt -u nullglob

# Diagnostics ISO/USB images are distributed separately, never bundled.

# App icon (generated by scripts/make_icon.sh).
[ -f "$ROOT/Assets/AppIcon.icns" ] && cp "$ROOT/Assets/AppIcon.icns" "$RES_DIR/AppIcon.icns"

# Bundle third-party tools (wimlib, mke2fs, ventoy, uefi-ntfs) if fetched.
if [ -d "$ROOT/vendor" ] && [ -n "$(ls -A "$ROOT/vendor" 2>/dev/null)" ]; then
  mkdir -p "$RES_DIR/thirdparty"
  cp -R "$ROOT/vendor/." "$RES_DIR/thirdparty/"
  echo "  bundled third-party tools from vendor/"
fi

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>$APP_NAME</string>
  <key>CFBundleDisplayName</key><string>$APP_NAME</string>
  <key>CFBundleIdentifier</key><string>$BUNDLE_ID</string>
  <key>CFBundleExecutable</key><string>$APP_NAME</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>$VERSION</string>
  <key>CFBundleVersion</key><string>$BUILD_NUM</string>
  <key>LSMinimumSystemVersion</key><string>26.0</string>
  <key>NSRemovableVolumesUsageDescription</key><string>Macus needs access to your selected USB to create bootable media and read saved diagnostic reports.</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>LSApplicationCategoryType</key><string>public.app-category.utilities</string>
  <key>CFBundleIconFile</key><string>AppIcon</string>
  <key>NSHumanReadableCopyright</key><string>© SynapsEdge. Portions © Harith Dilshan. GPLv3.</string>
</dict>
</plist>
PLIST

printf 'APPL????' > "$APP/Contents/PkgInfo"

echo "▶ Ad-hoc code signing…"
codesign --force --deep --sign - "$APP" >/dev/null 2>&1 && echo "  signed (ad-hoc)" || echo "  (codesign skipped)"

echo "✅ Built $APP  (v$VERSION build $BUILD_NUM)"
